C645 Test Days loan period (vega)
folio-org/stripes-testing pull request #1581
Opened 2023-09-12 12:57 UTC by ernestyedigaryan1

[C645](https://foliotest.testrail.io/index.php?/cases/view/645&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=103)

[Allure Report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4261/allure/#suites/ea5fbc3c562dc43e8c73370e25c83354)

2023-09-12 14:51 UTC, dnovikau approved these changes
LGTM

2023-09-13 10:03 UTC, ostapwd requested changes

2023-09-13 10:03 UTC, ostapwd commented on cypress/support/fragments/inventory/inventoryInstances.js
please move to cypress/support/api

2023-09-13 10:13 UTC, ostapwd approved these changes

2023-09-13 11:01 UTC, merged