FIX-399077
folio-org/stripes-testing pull request #1675
Opened 2023-09-26 14:41 UTC by dnovikau

[C399077](https://foliotest.testrail.io/index.php?/cases/view/399077)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4426/allure/)
***

2023-09-26 15:41 UTC, ostapwd approved these changes

2023-09-27 07:10 UTC, nayimovag requested changes

2023-09-27 07:10 UTC, nayimovag commented on cypress/e2e/settings/tenant/settings-remain-for-library.cy.js
test is failing https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4448/allure/

2023-09-27 09:33 UTC, dnovikau commented on cypress/e2e/settings/tenant/settings-remain-for-library.cy.js
Fixed. Test failed because element locator was changed.
Currently test is not passing on "https://folio-testing-cypress-diku.ci.folio.org/" because of big amoun of outdated data.

Report from snapshot env: https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4453/allure/

2023-09-28 11:10 UTC, nayimovag approved these changes

2023-09-28 13:37 UTC, merged