C588 Check in: at service point not assigned to item's effective location (vega) (TaaS)
folio-org/stripes-testing pull request #1676
Opened 2023-09-26 15:30 UTC by ernestyedigaryan1

[C588](https://foliotest.testrail.io/index.php?/cases/view/588)

[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4440/allure/)

2023-09-26 16:05 UTC, dnovikau commented on cypress/e2e/checkin/check-in-service-point-not-assigned.cy.js
> +import permissions from '../../support/dictionary/permissions';
this import is redundant

2023-09-28 16:46 UTC, manowarqqq approved these changes

2023-09-28 16:52 UTC, dnovikau requested changes
I'd recommend to refactor the test by using newly added function for generation and creation of folio instances.

Example: cypress/e2e/loans/export-loans.cy.js

2023-09-28 16:54 UTC, dnovikau commented on cypress/e2e/checkin/check-in-service-point-not-assigned.cy.js
> +    cy.createTempUser([Permissions.checkinAll.gui, Permissions.loansView.gui], patronGroup.name)
Permissions.loansView - is not mentioned in testcase

2023-09-28 16:54 UTC, dnovikau commented on cypress/e2e/checkin/check-in-service-point-not-assigned.cy.js
> +    { tags: [TestTypes.criticalPath, DevTeams.vega, Parallelization.nonParallel] },
Is Parallelization.nonParallel required?

2023-09-29 12:50 UTC, dnovikau approved these changes

2023-09-29 17:55 UTC, merged