C581-change loan due dates
folio-org/stripes-testing pull request #1696
Opened 2023-09-28 12:22 UTC by tomleexx

add new test scripts for C581

use this enviornment https://folio-snapshot-2-okapi.dev.folio.org to run scripts

testrail link
https://foliotest.testrail.io/index.php?/cases/view/581

Allure report
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4470/allure/#

2023-09-28 12:30 UTC, nayimovag requested changes

2023-09-28 12:30 UTC, nayimovag commented on cypress/e2e/loans/loan-change-due-dates.cy.js
> +    { tags: [TestTypes.smoke, DevTeams.volaris] },
wrong testType and devTeam

2023-09-28 12:30 UTC, nayimovag commented on cypress.config.js
> +    baseUrl: 'https://folio-snapshot-2.dev.folio.org/',
please don't change cypress configurations

2023-09-28 12:30 UTC, nayimovag commented on cypress/e2e/loans/loan-change-due-dates.cy.js
> +      Permissions.requestsAll.gui,
wrong set of permissions

2023-09-28 13:22 UTC, manowarqqq approved these changes

2023-09-28 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/stripes-testing?pullRequest=1696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/stripes-testing?pullRequest=1696) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tomleexx<br/>:x: Scorpibear<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/stripes-testing?pullRequest=1696) it.</sub>

2023-09-29 04:28 UTC, tomleexx commented on cypress/e2e/loans/loan-change-due-dates.cy.js
> +      Permissions.requestsAll.gui,
remove request permission

2023-09-29 04:32 UTC, tomleexx commented
Permissions: view loans, edit loans
User with at least one open loan for item with item status Checked out needed

according to preconditions,I just use loan.all permission and check out permission

2023-09-29 14:24 UTC, ernestyedigaryan1 approved these changes

2023-09-29 17:31 UTC, ostapwd approved these changes

2023-09-29 17:34 UTC, ostapwd approved these changes

2023-09-29 17:38 UTC, merged