[C2346] Delete an existing action profile (folijet) (TaaS)
folio-org/stripes-testing pull request #1816
Opened 2023-10-11 07:10 UTC by AliaksandrShuleika

[testrail](https://foliotest.testrail.io/index.php?/cases/view/2346)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4734/allure/#suites/0f29a4212ddbc0a40cf0646f9bcb6758/55b58e8835de5e79/)

2023-10-11 08:46 UTC, TetianaParanich commented on cypress/e2e/data-import/settings/delete-an-existing-action-profile.cy.js
> +        NewFieldMappingProfile.createMappingProfileViaApi(profile.createMappingProfile).then(
You shouldn't create all profiles, you need to create only action profile

2023-10-11 17:08 UTC, dnovikau requested changes

2023-10-12 07:21 UTC, dnovikau commented on cypress/e2e/data-import/settings/delete-an-existing-action-profile.cy.js
> +        NewFieldMappingProfile.createMappingProfileViaApi(profile.createMappingProfile).then(
Comment is not valid

2023-10-12 07:21 UTC, dnovikau approved these changes

2023-10-13 06:31 UTC, TetianaParanich approved these changes

2023-10-13 11:28 UTC, merged