C353638 Verify proper system behavior for canceled import (Folijet) (TaaS)
folio-org/stripes-testing pull request #1868
Opened 2023-10-15 17:19 UTC by TatianaOne

https://foliotest.testrail.io/index.php?/cases/view/353638

2023-10-17 10:59 UTC, Scorpibear requested changes
execution result attachment missed

2023-10-20 14:56 UTC, Scorpibear approved these changes

2023-10-20 15:52 UTC, Sherzod-Kenjaev approved these changes

2023-10-21 08:08 UTC, IhorBohdan approved these changes

2023-10-21 08:54 UTC, merged