C587 Check in: backdate check ins (vega) (TaaS)
folio-org/stripes-testing pull request #1956
Opened 2023-10-20 16:51 UTC by ernestyedigaryan1

[C587](https://foliotest.testrail.io/index.php?/cases/view/587)

[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4981/allure)

2023-10-24 10:49 UTC, dnovikau requested changes

2023-10-24 10:49 UTC, dnovikau commented on cypress/support/fragments/check-in-actions/checkInActions.js
> +const dateField = TextField({ id: 'dp-4' });
It seams that it's autogenerated id and it can be different on various environments

2023-10-24 10:49 UTC, dnovikau commented on cypress/e2e/checkin/check-in-backdate.cy.js
> +    { tags: [TestTypes.smoke, DevTeams.vega] },
Test type should be extended

2023-10-25 15:22 UTC, dnovikau approved these changes

2023-10-26 07:48 UTC, re-jas approved these changes

2023-10-26 08:35 UTC, merged