Fat 375258 Query search | Search by "Series" field of linked "MARC Bib" record (spitfire)
folio-org/stripes-testing pull request #2026
Opened 2023-10-24 18:14 UTC by manowarqqq

https://foliotest.testrail.io/index.php?/cases/view/375258

2023-10-31 06:57 UTC, ernestyedigaryan1 approved these changes

2023-11-02 08:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/stripes-testing?pullRequest=2026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/stripes-testing?pullRequest=2026) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/stripes-testing?pullRequest=2026) it.</sub>

2023-11-06 16:10 UTC, zentestuken requested changes
Also, please merge the latest master and verify test is passing with latest updates (see https://github.com/folio-org/stripes-testing/pull/2200). Some of your files may also require similar updates

2023-11-09 18:26 UTC, manowarqqq commented on cypress/e2e/inventory/search/search-by-series-field-of-linked-record.cy.js
> +      cy.getAdminToken();
done

2023-11-09 18:26 UTC, manowarqqq commented on cypress/e2e/inventory/search/search-by-series-field-of-linked-record.cy.js
> +      Users.deleteViaApi(testData.user.userId);
done

2023-11-09 19:22 UTC, manowarqqq commented
> Also, please merge the latest master and verify test is passing with latest updates (see #2200). Some of your files may also require similar updates

https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5374/allure/#suites
![image](https://github.com/folio-org/stripes-testing/assets/50654975/e2683fca-d9a2-46ad-8e3a-331ee2286403)

2023-11-10 09:00 UTC, zentestuken approved these changes

2023-11-10 09:46 UTC, merged