C353209 Export failed when using .csv file with non-existent UUIDs (Spitfire)
folio-org/stripes-testing pull request #2167
Opened 2023-11-02 14:06 UTC by arsenhovh

[Test Rail](https://foliotest.testrail.io/index.php?/cases/view/353209)
[Allure Report](url)

2023-11-06 10:57 UTC, Sherzod-Kenjaev requested changes

2023-11-06 10:57 UTC, Sherzod-Kenjaev commented on cypress/support/fragments/marcAuthority/marcAuthority.js
> +  },
There are already existing methods to delete marc authority record in marcAuthoritiesDelete.js file please use them.

2023-11-06 10:57 UTC, Sherzod-Kenjaev commented on cypress/support/fragments/marcAuthority/marcAuthorities.js
> +    cy.do([actionsButton.click(), Button('Export selected records (CSV/MARC)').click()]);
Move interactor  Button('Export selected records (CSV/MARC)') to const variable please.

2023-11-06 10:57 UTC, Sherzod-Kenjaev commented on cypress/e2e/data-export/export-failed-using-non-existent-UUIDs.cy.js
> +      Permissions.dataExportEnableModule.gui,
Use required permissions, in test case it is asked to use three permissions.

2023-11-06 11:59 UTC, Sherzod-Kenjaev approved these changes

2023-11-06 16:18 UTC, zentestuken reviewed
Please fix linter issues

2023-11-07 07:43 UTC, zentestuken approved these changes

2023-11-07 07:52 UTC, merged