C400617 Search Holdings using advanced search with "AND" operator (spitfire) (TaaS)
folio-org/stripes-testing pull request #2196
Opened 2023-11-06 07:31 UTC by artsiomBandarenka

[C400617 ](https://foliotest.testrail.io/index.php?/cases/view/400617)

[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5271/allure/#suites)

![image](https://github.com/folio-org/stripes-testing/assets/145689331/6d8ba180-8b30-4520-8444-f6309e2d0190)

2023-11-10 14:26 UTC, Scorpibear requested changes
Please, spread the comment between actual code which do specific action from the precondition. Original comment could be reduced to key points, where possible

2023-11-10 14:31 UTC, Scorpibear requested changes
please, update comment to more concise version, e.g.
// #3-#5 check advanced search dropdowns, including operator, search modifier, etc...

2023-11-13 11:53 UTC, Scorpibear approved these changes

2023-11-14 06:36 UTC, zentestuken approved these changes

2023-11-14 06:46 UTC, Sherzod-Kenjaev approved these changes

2023-11-14 07:14 UTC, merged