C353529 Verify progress bar for uploading identifier files(firebird) …
folio-org/stripes-testing pull request #2241
Opened 2023-11-09 09:52 UTC by KarapetyanSofia

[C353529](https://foliotest.testrail.io/index.php?/cases/view/353529)

2023-11-10 10:33 UTC, nayimovag commented on cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-progress-bar.cy.js
> +        BulkEditSearchPane.verifyPopulatedPreviewPage();
please verify the progress bar described in the second step of the TC

2023-11-13 10:36 UTC, manowarqqq approved these changes

2023-11-13 10:36 UTC, manowarqqq commented on cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
> +  verifyPopulatedPreviewPage() {
Please, use array of assertions
Example:
 cy.expect([
      deleteUploadedFileModal.exists(),
      deleteUploadedFileModal.find(HTML(including(modalContent))).exists(),
      deleteUploadedFileModal.find(modalNoButton, { disabled: true }).exists(),
      deleteUploadedFileModal.find(modalYesButton, { disabled: false }).exists(),
    ]);

2023-11-13 10:36 UTC, manowarqqq reviewed
Please, Add link from Jenkins with screenshot

2023-11-13 10:37 UTC, manowarqqq reviewed
-

2023-11-13 10:39 UTC, manowarqqq reviewed
-

2023-11-13 10:41 UTC, manowarqqq commented on cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-progress-bar.cy.js
> +        permissions.bulkEditLogsView.gui,
Permissions.bulkEditLogsView.gui,
        Permissions.bulkEditUpdateRecords.gui,
        Permissions.uiUserEdit.gui,

2023-11-13 10:42 UTC, manowarqqq requested changes

2023-11-13 10:42 UTC, manowarqqq commented on cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-progress-bar.cy.js
> +      { tags: [testTypes.smoke, devTeams.firebird] },
{ tags: [TestTypes.smoke, DevTeams.firebird] },

2023-11-13 15:14 UTC, nayimovag approved these changes

2023-11-14 14:20 UTC, manowarqqq approved these changes

2023-11-14 16:26 UTC, merged