C365601 Cancel unlinking "MARC Bibliographic" field from "MARC Authority" record and use the "Cancel" button in editing window. (Spitfire) (TaaS)
folio-org/stripes-testing pull request #2272
Opened 2023-11-12 15:05 UTC by TatianaOne

https://foliotest.testrail.io/index.php?/cases/view/365601

2023-11-13 12:20 UTC, zentestuken approved these changes

2023-11-16 12:03 UTC, Scorpibear requested changes
CI execution results are missed

2023-11-18 07:17 UTC, TetianaParanich approved these changes

2023-11-19 13:24 UTC, Sherzod-Kenjaev approved these changes

2023-11-20 11:05 UTC, manowarqqq approved these changes

2023-11-20 12:33 UTC, Scorpibear approved these changes

2023-11-20 12:55 UTC, merged