C375139 Edit any field in linked MARC authority record without 010 field when 001 = $0 (Spitfire) (TaaS)
folio-org/stripes-testing pull request #2558
Opened 2023-12-01 15:12 UTC by ylatysh

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/375139)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6270/allure/)

![image](https://github.com/folio-org/stripes-testing/assets/151656597/ebd3d407-8865-40be-8e86-7435df188547)

2023-12-12 15:49 UTC, dnovikau approved these changes

2023-12-22 11:42 UTC, Sherzod-Kenjaev requested changes

2023-12-22 11:42 UTC, Sherzod-Kenjaev commented on cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-without-010-field-when-001-field-value-set-to-0.cy.js
> +
step 2 - Not all verifications were covered
![Screenshot 2023-12-22 163347](https://github.com/folio-org/stripes-testing/assets/114989418/3245d44a-080d-40b2-86b5-34a146acf1d1)

2023-12-22 11:42 UTC, Sherzod-Kenjaev commented on cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-without-010-field-when-001-field-value-set-to-0.cy.js
> +      QuickMarcEditor.checkAfterSaveAndCloseAuthority();
step 5 - cover all checks please
![Screenshot 2023-12-22 163817](https://github.com/folio-org/stripes-testing/assets/114989418/6f102de2-6565-4cff-bd94-f82a3a2651f8)

2023-12-22 11:42 UTC, Sherzod-Kenjaev commented on cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-without-010-field-when-001-field-value-set-to-0.cy.js
> +      InventoryInstances.selectInstance();
step 8 - check required results
![Screenshot 2023-12-22 163832](https://github.com/folio-org/stripes-testing/assets/114989418/9733d407-96fe-4f89-adf3-d4102caf8089)

2023-12-22 11:42 UTC, Sherzod-Kenjaev commented on cypress/support/fragments/inventory/inventoryInstances.js
> +    cy.expect(filterSection.find(searchButton).has({ disabled: false }));
Place cy.expect checks into array please, cy.expect([]);

2023-12-28 06:52 UTC, Sherzod-Kenjaev approved these changes

2023-12-28 07:31 UTC, TetianaParanich commented on cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-without-010-field-when-001-field-value-set-to-0.cy.js
> +    cy.loginAsAdmin({
Please add deleting marc auth record before
cy.getAdminToken();
      // make sure there are no duplicate authority records in the system
      MarcAuthorities.getMarcAuthoritiesViaApi({ limit: 100, query: 'keyword="C375139"' }).then(
        (records) => {
          records.forEach((record) => {
            if (record.authRefType === 'Authorized') {
              MarcAuthority.deleteViaAPI(record.id);
            }
          });
        },
      );
And add to the marcAuthFileForC375139.mrc in the field 100 $a id 'C375139'. It helps deleting duplicates of auth records in DB

2023-12-29 11:27 UTC, TetianaParanich approved these changes

2023-12-29 11:33 UTC, merged