C389484 Link headings button is NOT displayed in create MARC bib window when auto-link for all heading types is disabled (spitfire) (TaaS)
folio-org/stripes-testing pull request #2588
Opened 2023-12-05 09:08 UTC by elen2345

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/389484)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5824/allure/)
![image](https://github.com/folio-org/stripes-testing/assets/147595219/dccfa1ef-7ef9-4691-b310-8dce88be7401)

2023-12-05 12:34 UTC, dnovikau approved these changes

2023-12-12 06:51 UTC, zentestuken requested changes

2023-12-12 06:51 UTC, zentestuken commented on cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-button-disabled.cy.js
> +  after('Deleting created users, Instances', () => {
Could you please reset auto-linking rules after the test to default values, or just set them to `true` for all fields?

2023-12-12 14:50 UTC, zentestuken approved these changes

2023-12-12 15:06 UTC, merged