Added C369083 - Finance | Results List | Verify that values in "Name"…
folio-org/stripes-testing pull request #2692
Opened 2023-12-12 15:02 UTC by KazachenkaTatsiana

… columns are hyperlink

https://foliotest.testrail.io/index.php?/cases/view/369083

https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5970/console

![image](https://github.com/folio-org/stripes-testing/assets/139146179/c8785b23-a8c5-4a06-a994-d488ca2a5d72)

2023-12-14 12:28 UTC, manowarqqq commented on cypress/e2e/finance/name-columns-is-hyperlink.cy.js
> +      permissions.uiFinanceViewFiscalYear.gui,
Permissions. code convention

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/groups/groups.js
> +  selectGroupWithDetails: (GroupName) => {
selectGroupByName

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/financeHelper.js
> +  clickFunButton() {
Fund

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/financeHelper.js
> +  clickFiscalYearButton() {
Why not interactors?
Just Button('Fiscal year')

the same for rest

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/financeHelper.js
> +  waitLoading() {
Looks like it should be in Ledgers fragment

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/funds/funds.js
> +  verifyFunLikNameExists: (FundName) => {
FundLink

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/ledgers/ledgers.js
> +    cy.wait(4000);
why so long timeout?

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/ledgers/ledgers.js
> +  ledgerLinkExists: (name) => {
verify

2023-12-14 12:28 UTC, manowarqqq commented on cypress/support/fragments/finance/groups/groupDetails.js
> +import { PaneHeader, Section, including } from '../../../../../interactors';
Please add this file to fragments/finance/index.js

2023-12-18 08:38 UTC, manowarqqq approved these changes

2023-12-18 09:59 UTC, IhorBohdan commented on cypress/e2e/finance/name-columns-is-hyperlink.cy.js
> +      const FiscalYearDetails = FiscalYears.selectFisacalYear(defaultFiscalYear.name);
Why you move method to const?I don't understand

2023-12-18 10:02 UTC, IhorBohdan commented on cypress/support/fragments/finance/financeHelper.js
> +const fiscalYearButton = filtersPane.find(Button('Fiscal year'));
Please dont move full method to const...move only Button, textfield and another

2023-12-18 10:03 UTC, IhorBohdan requested changes
Fix my changes

2023-12-25 13:01 UTC, IhorBohdan approved these changes

2023-12-26 07:32 UTC, merged