C350414 Check that user can see "Requests" columns (vega) (TaaS)
folio-org/stripes-testing pull request #2768
Opened 2023-12-18 21:09 UTC by dzmitryshaplyka1

[C350414](https://foliotest.testrail.io/index.php?/cases/view/350414)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6093/allure/#suites/c5bef5aff157d294939143744c81de2b/816718ab56165e27/)
<img width="1611" alt="Screenshot 2023-12-19 at 00 08 15" src="https://github.com/folio-org/stripes-testing/assets/144434246/5441d268-2e98-4605-b1b1-233839615081">

2023-12-20 16:11 UTC, dnovikau approved these changes

2023-12-20 16:16 UTC, dnovikau requested changes
Please move this test to a separate file. Permissions for user in current file does not match expected list in test case

2023-12-21 08:14 UTC, dzmitryshaplyka1 commented
> Please move this test to a separate file. Permissions for user in current file does not match expected list in test case

Hi @dnovikau, thank you for the review, it is updated.
[New Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6193/allure/#suites/c5bef5aff157d294939143744c81de2b/28c0b2c9a6a678ec/)
<img width="1783" alt="Screenshot 2023-12-21 at 11 13 50" src="https://github.com/folio-org/stripes-testing/assets/144434246/c0470137-9934-45d6-ba32-95a1c384e100">

2023-12-24 06:56 UTC, dnovikau approved these changes

2023-12-26 13:53 UTC, re-jas approved these changes

2023-12-26 13:59 UTC, merged